version: '3.7'

services:
    gateway:
        image: baranbartu/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8001"
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        ports:
          - 8001:8001
        depends_on:
          - users
          - orders
        networks:
          - microservices
        volumes:
          - ./gateway:/app

    users:
        image: baranbartu/k-users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8002"
        build:
            context: ./users
            dockerfile: Dockerfile
        env_file:
            - ./users/.env
        ports:
          - 8002:8002
        networks:
          - microservices
        volumes:
          - ./users:/app

    orders:
        image: baranbartu/k-orders:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8003"
        build:
            context: ./orders
            dockerfile: Dockerfile
        env_file:
            - ./orders/.env
        ports:
          - 8003:8003
        networks:
          - microservices
        volumes:
          - ./orders:/app

networks:
  microservices:
    driver: bridge
